#!/usr/bin/env python3
"""Enforce RuntimeGuard coverage across all repos under a root directory.

Behavior:
- Discover git repositories under --root.
- For Python-capable repositories, ensure a RuntimeGuard-managed sitecustomize.py.
- For non-Python repositories, report as watcher-only coverage candidates.
- Write a JSON report with per-repo status and summary counts.
"""

from __future__ import annotations

import argparse
import json
import os
import uuid
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

from runtime_guard import make_sitecustomize_content


_RUNTIME_GUARD_MARKER = "Auto-generated by runtime_guard.make_sitecustomize_content()"
_PYTHON_HINT_FILES = {
    "pyproject.toml",
    "requirements.txt",
    "requirements-dev.txt",
    "setup.py",
    "setup.cfg",
    "Pipfile",
    "poetry.lock",
}


@dataclass
class RepoStatus:
    repo_path: str
    repo_name: str
    is_python_repo: bool
    status: str
    details: str
    sitecustomize_path: str | None = None


@dataclass
class ReportSummary:
    total_repos: int
    python_repos: int
    non_python_repos: int
    enforced: int
    already_enforced: int
    blocked_existing_sitecustomize: int
    dry_run_candidates: int
    watcher_only_candidates: int


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Enforce RuntimeGuard across repositories.")
    parser.add_argument("--root", required=True, help="Root directory to scan for repositories")
    parser.add_argument(
        "--report-path",
        default="reports/repo_guard_enforcement.json",
        help="Path to write JSON report",
    )
    parser.add_argument("--stage", default="repo-autostart")
    parser.add_argument("--interval-s", type=float, default=30.0)
    parser.add_argument("--cooldown-s", type=float, default=30.0)
    parser.add_argument("--env-prefix", default="RUNTIME_GUARD")
    parser.add_argument("--posture", default="wsl_dev")
    parser.add_argument(
        "--enforce-all-repos",
        action="store_true",
        help="Apply RuntimeGuard sitecustomize.py to all repos, including non-Python repos.",
    )
    parser.add_argument(
        "--force-runtime-guard-sitecustomize",
        action="store_true",
        help="Overwrite existing sitecustomize.py only when it already contains RuntimeGuard marker.",
    )
    parser.add_argument(
        "--run-id",
        default="",
        help="Optional external run identifier for cross-artifact correlation.",
    )
    parser.add_argument("--dry-run", action="store_true", help="Report actions without writing files")
    return parser.parse_args()


def _discover_git_repos(root: Path) -> list[Path]:
    repos: list[Path] = []
    for dirpath, dirnames, _filenames in os.walk(root):
        if ".git" in dirnames:
            repos.append(Path(dirpath))
            dirnames[:] = [d for d in dirnames if d != ".git"]
            continue
        dirnames[:] = [d for d in dirnames if d != ".git"]
    return sorted(repos)


def _is_python_repo(repo_path: Path) -> bool:
    for marker in _PYTHON_HINT_FILES:
        if (repo_path / marker).exists():
            return True
    for candidate in repo_path.iterdir():
        if candidate.is_file() and candidate.suffix == ".py":
            return True
    src_dir = repo_path / "src"
    if src_dir.is_dir():
        for py_file in src_dir.rglob("*.py"):
            if py_file.is_file():
                return True
    return False


def _read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return path.read_text(encoding="latin-1")


def _enforce_sitecustomize(repo_path: Path, args: argparse.Namespace) -> RepoStatus:
    site_path = repo_path / "sitecustomize.py"
    if site_path.exists():
        current = _read_text(site_path)
        managed = _RUNTIME_GUARD_MARKER in current
        if managed and args.force_runtime_guard_sitecustomize:
            if args.dry_run:
                return RepoStatus(
                    repo_path=str(repo_path),
                    repo_name=repo_path.name,
                    is_python_repo=True,
                    status="dry_run_candidate",
                    details="Would refresh RuntimeGuard-managed sitecustomize.py",
                    sitecustomize_path=str(site_path),
                )
            content = make_sitecustomize_content(
                repo_name=repo_path.name,
                stage=args.stage,
                interval_s=args.interval_s,
                cooldown_s=args.cooldown_s,
                env_prefix=args.env_prefix,
                posture=args.posture,
            )
            site_path.write_text(content, encoding="utf-8")
            return RepoStatus(
                repo_path=str(repo_path),
                repo_name=repo_path.name,
                is_python_repo=True,
                status="enforced",
                details="Refreshed RuntimeGuard-managed sitecustomize.py",
                sitecustomize_path=str(site_path),
            )
        if managed:
            return RepoStatus(
                repo_path=str(repo_path),
                repo_name=repo_path.name,
                is_python_repo=True,
                status="already_enforced",
                details="RuntimeGuard-managed sitecustomize.py already present",
                sitecustomize_path=str(site_path),
            )
        return RepoStatus(
            repo_path=str(repo_path),
            repo_name=repo_path.name,
            is_python_repo=True,
            status="blocked_existing_sitecustomize",
            details="sitecustomize.py exists but is not RuntimeGuard-managed",
            sitecustomize_path=str(site_path),
        )

    if args.dry_run:
        return RepoStatus(
            repo_path=str(repo_path),
            repo_name=repo_path.name,
            is_python_repo=True,
            status="dry_run_candidate",
            details="Would create RuntimeGuard-managed sitecustomize.py",
            sitecustomize_path=str(site_path),
        )

    content = make_sitecustomize_content(
        repo_name=repo_path.name,
        stage=args.stage,
        interval_s=args.interval_s,
        cooldown_s=args.cooldown_s,
        env_prefix=args.env_prefix,
        posture=args.posture,
    )
    site_path.write_text(content, encoding="utf-8")
    return RepoStatus(
        repo_path=str(repo_path),
        repo_name=repo_path.name,
        is_python_repo=True,
        status="enforced",
        details="Created RuntimeGuard-managed sitecustomize.py",
        sitecustomize_path=str(site_path),
    )


def _summarize(statuses: list[RepoStatus]) -> ReportSummary:
    return ReportSummary(
        total_repos=len(statuses),
        python_repos=sum(1 for s in statuses if s.is_python_repo),
        non_python_repos=sum(1 for s in statuses if not s.is_python_repo),
        enforced=sum(1 for s in statuses if s.status == "enforced"),
        already_enforced=sum(1 for s in statuses if s.status == "already_enforced"),
        blocked_existing_sitecustomize=sum(
            1 for s in statuses if s.status == "blocked_existing_sitecustomize"
        ),
        dry_run_candidates=sum(1 for s in statuses if s.status == "dry_run_candidate"),
        watcher_only_candidates=sum(1 for s in statuses if s.status == "watcher_only_candidate"),
    )


def main() -> int:
    args = _parse_args()
    root = Path(args.root).expanduser().resolve()
    if not root.is_dir():
        raise SystemExit(f"error: root path does not exist: {root}")

    repos = _discover_git_repos(root)
    statuses: list[RepoStatus] = []

    for repo in repos:
        is_python = _is_python_repo(repo)
        if is_python or args.enforce_all_repos:
            statuses.append(_enforce_sitecustomize(repo, args))
            continue
        statuses.append(
            RepoStatus(
                repo_path=str(repo),
                repo_name=repo.name,
                is_python_repo=False,
                status="watcher_only_candidate",
                details="No Python markers detected; cover via runtime_guard_repo_watcher",
                sitecustomize_path=None,
            )
        )

    summary = _summarize(statuses)
    run_id = str(args.run_id or "").strip()
    if not run_id:
        run_id = str(uuid.uuid4())
    summary_payload = asdict(summary)
    summary_payload["run_id"] = run_id
    payload: dict[str, Any] = {
        "root": str(root),
        "run_id": run_id,
        "stage": args.stage,
        "env_prefix": args.env_prefix,
        "posture": args.posture,
        "dry_run": bool(args.dry_run),
        "summary": summary_payload,
        "repos": [asdict(s) for s in statuses],
    }

    report_path = Path(args.report_path)
    if not report_path.is_absolute():
        report_path = Path.cwd() / report_path
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")

    print(json.dumps(payload["summary"], indent=2, sort_keys=True))
    print(f"report: {report_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
